version: "3.8"

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      SECRET_KEY: "dev-secret-key"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
    volumes:
      - .:/app
